[package]
name = "akita"
version = "0.1.0"
authors = ["Colin Reeder <colin@vpzom.click>"]
edition = "2018"

[dependencies]
postgres = "0.15.2"
acme-client = { git = "https://github.com/janderholm/acme-client", rev = "18009de" }
reqwest = "0.9.18"
